### ISSUE TITLE
Create banner

### ISSUE THREAD

**Issue by metakermit** [Borders-None/bookshop-project-2020-autumn#1]
![Screenshot 2020-11-26 at 19 50 53](https://user-images.githubusercontent.com/1818628/100384550-b6ddad80-3020-11eb-9855-4b49bfeab118.png)

**Comment by haniscape** [comment]
![banner-image](https://user-images.githubusercontent.com/16334871/100998944-715b3c00-355c-11eb-94c5-2f6062b16050.jpg)
I reduced the image size using Adobe Photoshop to reduce loading time. same dimentions are used but density is now 300

**Comment by haniscape** [comment]
about the dark effect I used a pseudo element acting as a background to apply brightness filter without that reflecting the banner text, I used the trick mentioned : [here](https://css-tricks.com/apply-a-filter-to-a-background-image/)
