### ISSUE TITLE
styling a bit modified with blue accent - login 

### ISSUE THREAD

**Issue by haniscape** [Borders-None/bookshop-project-2020-autumn#22]
Dear All,
I would like to suggest adding blue accent to the design to enhance look appeal.
Also a bigger footer with Organizers and Students links will be added.

tell me your opinion.

p.s. As per request from Josip, I didnot centralized the style in one main.css; instead every folder will have its own:
html, css and js files respectively.

**Comment by AhmadAlkaati** [comment]
Great Idea !! I agree with you on this idea Hany :)

**Comment by haniscape** [comment]
Thanks Ahmed , I did the latest touches for the header and footer, 
also the buttons now has the blue touch.

**Comment by AhmadAlkaati** [comment]
Ok nice, then this issue is done
